services:
  pyapp:
    container_name: pyapp
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./app:/app   # ← ここを1本にする
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: run.py
      FLASK_ENV: development
    depends_on:
      pydb:
        condition: service_healthy

  pydb:
    image: mysql:8.0
    container_name: pydb
    ports: 
      - "3306:3306"
    volumes:
      - pydb-data:/var/lib/mysql # init.sqlを使用する場合は名前付きボリュームを作成
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pydb
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot"] # mysとの疎通確認コマンド
      interval: 5s
      timeout: 60s
      retries: 5

volumes:
  pydb-data: # 名前付きボリューム指定